// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWj_blFRu-nEKY6VfN3TAqK0UQnRDnNf0',
    appId: '1:1056939777168:web:8338137eac3779008f4c15',
    messagingSenderId: '1056939777168',
    projectId: 'skripsi-6f26d',
    authDomain: 'skripsi-6f26d.firebaseapp.com',
    databaseURL: 'https://skripsi-6f26d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'skripsi-6f26d.appspot.com',
    measurementId: 'G-N2N639WC0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKvH9MhzXIoE90KxCvLGhtGIAheyTLjgc',
    appId: '1:1056939777168:android:50c352287a83e64f8f4c15',
    messagingSenderId: '1056939777168',
    projectId: 'skripsi-6f26d',
    databaseURL: 'https://skripsi-6f26d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'skripsi-6f26d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASNTCsDHkb9URIlyNolgYqoZYBhiNrpgs',
    appId: '1:1056939777168:ios:5b3514213b7c85c58f4c15',
    messagingSenderId: '1056939777168',
    projectId: 'skripsi-6f26d',
    databaseURL: 'https://skripsi-6f26d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'skripsi-6f26d.appspot.com',
    iosClientId: '1056939777168-03g6vuvaer05018kjsc8pmij1ma5utgb.apps.googleusercontent.com',
    iosBundleId: 'com.example.kontroller',
  );
}
